export const REGISTER_REQUEST =' REGISTER_ REQUEST' ;
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS' ;
export const REGISTER_FAILURET ='REGISTER_FAILURE';


export const LOGIN_REQUEST =' LOGIN_ REQUEST' ;
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS' ;
export const LOGIN_FAILURET ='LOGIN_FAILURE';


export const GET_USER_REQUEST =' GET_USER_ REQUEST' ;
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS' ;
export const GET_USER_FAILURET ='GET_USER_FAILURE';

export const LOGOUT='LOGOUT';



